# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('tooltip', models.CharField(default='', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(default='', max_length=512)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('versionInit', models.CharField(max_length=128)),
                ('client_ip', models.GenericIPAddressField(default='1.1.1.1')),
                ('keywords', models.CharField(default='', max_length=256)),
                ('json', models.CharField(default='', max_length=10000)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(to='data.Category')),
            ],
        ),
    ]
