# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='delete_id',
            field=models.CharField(default='-1', max_length=128),
        ),
    ]
