# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-12 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_workflow_delete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='delete_id',
            field=models.CharField(default='-1', max_length=128, null=True),
        ),
    ]
