;**************************************************************************
; PRACTICA 4, EJERCICIO B -> TOMAS HIGUERA VISO Y GUILLERMO HOYO BRAVO, PAREJA 1
;**************************************************************************
; DEFINICION DEL SEGMENTO DE DATOS
	DATOS SEGMENT
		info1 DB "Cadena a decodificar: ",'$'
		info2 DB "Cadena a codificar: ",'$'
		intro DB 13,10,'$'
		cadena_decodificar DB "EP1ERHEPYW VYPIW",'$'
		cadena_codificar DB "KLK DICE EL CESAR",'$'
	DATOS ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE PILA
	PILA SEGMENT STACK "STACK"
		DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
	PILA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO EXTRA
	EXTRA SEGMENT
		RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
	EXTRA ENDS
;************************************************************************** 
; DEFINICION DEL SEGMENTO DE CODIGO
	CODE SEGMENT
		ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
INICIO PROC
; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
	MOV AX, DATOS
	MOV DS, AX
	MOV AX, PILA
	MOV SS, AX
	MOV AX, EXTRA
	MOV ES, AX
	MOV SP, 64
; FIN DE LAS INICIALIZACIONES
	
; COMIENZO DEL PROGRAMA
	; IMPRIMIMOS INFO SOBRE LO QUE VAMOS A HACER
	CALL imprimir_info2
	; IMPRIMIMOS LA CADENA QUE VAMOS A CODIFICAR
	CALL imprimir_codificar
	; IMPRIMIMOS INTRO
	CALL imprimir_intro
	; GUARDAMOS EN DX EL OFFSET DE LA CADENA A CODIFICAR
	MOV DX, OFFSET cadena_codificar
	; GUARDAMOS EN AH 1 PARA CODIFICAR
	MOV AH, 1
	; LLAMAMOS A LA INTERRUPCION
	INT 60h
	; IMPRIMIMOS INTRO
	CALL imprimir_intro
	; IMPRIMIMOS INFO SOBRE LO QUE VAMOS A HACER
	CALL imprimir_info1
	; IMPRIMIMOS LA CADENA QUE VAMOS A DECODIFICAR
	CALL imprimir_decodificar
	; IMPRIMIMOS EL INTRO
	CALL imprimir_intro
	; GUARDAMOS EN DX EL OFFSET DE LA CADENA A DECODIFICAR
	MOV DX, OFFSET cadena_decodificar
	; GUARDAMOS EN AH 2 PARA DECODIFICAR
	MOV AH, 2
	; LLAMAMOS A LA INTERRUPCION
	INT 60h
	; SALTAMOS A LA RUTINA DE FIN DE PROGRAMA
	JMP fin
; FIN DEL PROGRAMA
fin:
	MOV AX, 4C00H
	INT 21H
	INICIO ENDP
	
imprimir_codificar PROC
	; GUARDAMOS EN DX EL OFFSET DEL STRING QUE VAMOS A IMPRIMIR
	MOV DX, OFFSET cadena_codificar
	; GUARDAMOS EN AH 9 PARA IMPRIMIR CON LA INTERRUPCION 21h
	MOV AH, 9
	; IMPRIMIMOS LLAMANDO A LA INTERRUPCION 21h
	INT 21h
	; VOLVEMOS DONDE SE HA LLAMADO LA RUTINA
	RET
imprimir_codificar ENDP

imprimir_info1 PROC
	; GUARDAMOS EN DX EL OFFSET DEL STRING QUE VAMOS A IMPRIMIR
	MOV DX, OFFSET info1
	; GUARDAMOS EN AH 9 PARA IMPRIMIR CON LA INTERRUPCION 21h
	MOV AH, 9
	; IMPRIMIMOS LLAMANDO A LA INTERRUPCION 21h
	INT 21h
	; VOLVEMOS DONDE SE HA LLAMADO LA RUTINA
	RET
imprimir_info1 ENDP

imprimir_info2 PROC
	; GUARDAMOS EN DX EL OFFSET DEL STRING QUE VAMOS A IMPRIMIR
	MOV DX, OFFSET info2
	; GUARDAMOS EN AH 9 PARA IMPRIMIR CON LA INTERRUPCION 21h
	MOV AH, 9
	; IMPRIMIMOS LLAMANDO A LA INTERRUPCION 21h
	INT 21h
	; VOLVEMOS DONDE SE HA LLAMADO LA RUTINA
	RET
imprimir_info2 ENDP

imprimir_intro PROC
	; GUARDAMOS EN DX EL OFFSET DEL STRING QUE VAMOS A IMPRIMIR
	MOV DX, OFFSET intro
	; GUARDAMOS EN AH 9 PARA IMPRIMIR CON LA INTERRUPCION 21h
	MOV AH, 9
	; IMPRIMIMOS LLAMANDO A LA INTERRUPCION 21h
	INT 21h
	; VOLVEMOS DONDE SE HA LLAMADO LA RUTINA
	RET
imprimir_intro ENDP

imprimir_decodificar PROC
	; GUARDAMOS EN DX EL OFFSET DEL STRING QUE VAMOS A IMPRIMIR
	MOV DX, OFFSET cadena_decodificar
	; GUARDAMOS EN AH 9 PARA IMPRIMIR CON LA INTERRUPCION 21h
	MOV AH, 9
	; IMPRIMIMOS LLAMANDO A LA INTERRUPCION 21h
	INT 21h
	; VOLVEMOS DONDE SE HA LLAMADO LA RUTINA
	RET
imprimir_decodificar ENDP
; FIN DEL SEGMENTO DE CODIGO
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO