-- PRIMERA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status is null;

-- SEGUNDA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status ='Shipped';

-- CREAMOS UN INDICE CON LA CLUMNA STATUS DE LA TABLA ORDERS
CREATE INDEX index_status on orders(status);

-- VOLVEMOS A EJECUTRA LAS MISMAS SENTENCIAS EXPLAIN QUE HEMOS REALIZADO ANTES
-- PRIMERA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status is null;

-- SEGUNDA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status ='Shipped';

-- EJECUTAMOS AHORA LA SENTENCIA ANALYZE EN LA TABLA ORDERS
ANALYZE orders;

-- VOLVEMOS A EJECUTAR LAS MISMAS SENTENCIAS DEL PRIMER APRATADO
-- PRIMERA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status is null;

-- SEGUNDA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status ='Shipped';

-- EJECUTAMOS LA SENTENCIA EXPLAIN CON LAS OTRAS DOS CONSULTAS DEL APENDICE 2
-- TERCERA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status ='Paid';

-- CUARTA CONSULTA DEL APENDICE 2
EXPLAIN SELECT count(*) FROM orders WHERE status ='Processed';