;**************************************************************************
; SBM 2015. ESTRUCTURA BÁSICA DE UN PROGRAMA EN ENSAMBLADOR
;**************************************************************************
	; DEFINICION DEL SEGMENTO DE DATOS
	DATOS SEGMENT
		;-- rellenar con los datos solicitados
	DATOS ENDS
	;**************************************************************************
	; DEFINICION DEL SEGMENTO DE PILA
	PILA SEGMENT STACK "STACK"
		DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
	PILA ENDS
	;**************************************************************************
	; DEFINICION DEL SEGMENTO EXTRA
	EXTRA SEGMENT
		RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
	EXTRA ENDS
	;**************************************************************************
	; DEFINICION DEL SEGMENTO DE CODIGO
	CODE SEGMENT
	ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
	; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
	INICIO PROC
	; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
	; INICIALIZAMOS AX CON EL VALOR 0535H PARA INICIALIZAR EL DS
	MOV AX, 0535H
	; INICIALIZAMOS EL DS CON EL VALOR 0535H
	MOV DS, AX
	MOV AX, PILA
	MOV SS, AX
	MOV AX, EXTRA
	MOV ES, AX
	MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
	; FIN DE LAS INICIALIZACIONES
	; COMIENZO DEL PROGRAMA
	; INICIALIZAMOS BX CON EL VALOR 0210H
	MOV BX, 0210H
	; INICIALIZAMOS DI CON EL VALOR 1011H
	MOV DI, 1011H
	; GUARDAMOS EN AL EL VALOR CONTENIDO EN LA POSICION DE MEMORIA 06584H
	MOV AL,DS:[1234H]
	; GUARDAMOS EN AX EL VALOR QUE CONTIENE LA POSICION DE MEMORIA 05560H[EQUIVALENTE A DS + BX]
	MOV AX,[BX]
	; GUARDAMOS AL EN LA POSICION DE MEMORIA 06361H[EQUIVALENTE A DS + DI]
	MOV [DI],AL
	; FIN DEL PROGRAMA
	MOV AX, 4C00H
	INT 21H
	INICIO ENDP
	; FIN DEL SEGMENTO DE CODIGO
	CODE ENDS
	; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
	END INICIO 