#ifndef SENIALES_H
#define SENIALES_H
    
/*ESTE MANEJADOR SE UTILIZARA PARA RECIBIR LA SENIAL DE FIN DE PROGRAMA(CTRL + C)*/
void manejador_SIGINT(int sig);

/*ESTE MANEJADOR SE UTILIZARA PARA RECIBIR LA SENIAL DE FIN DE TIEMPO DE ESPERA PARA REALIZAR APUESTAS*/
void manejador_SIGUSR1(int sig);

/*ESTE MANEJADOR SE UTILIZARA PARA CONTAR LA CANTIDAD DE CABALLOS QUE SE HAN GENERADO*/
void manejador_SIGUSR2(int sig);

/*ESTE MANEJADOR SE UTILIZARA PARA INFORMAR A LOS CABALLOS DE QUE EL PROCESO PRINCIPAL SE ENCUENTRA EN ESPERA*/
void manejador_SIGALALRM(int sig);

/*ESTE MANEJADOR SE UTILIZARA PARA INFORMAR A LOS PROCESOS DE QUE UNO DE LOS CABALLOS HA LLEGADO A LA META*/
void manejador_SIGTERM(int sig);

/*ESTE MANEJADOR SE UTILIZARA PARA AVISAR AL PROCESO PRINCIPAL DE QUE LOS CABLLOS YA HAN REALIZADO SUS TIRADAS*/
void manejador_SIGTRAP(int sig);

#endif