;********************************************************************************
; PRACTICA 3, EJERCICIO A -> TOMAS HIGUERA VISO Y GUILLERMO HOYO BRAVO, PAREJA 1*
;********************************************************************************
; DEFINICION DEL SEGMENTO DE CODIGO                                             *
;********************************************************************************

PRACT3B SEGMENT BYTE PUBLIC 'CODE'
	PUBLIC _calcularAciertos, _calcularSemiaciertos
	ASSUME CS: PRACT3B
	
		_calcularAciertos PROC FAR
			; PUSHEAMOS BP EN LA PILA
			PUSH BP
			; GUARDAMOS EN BP EL STACK POINTER DE LA PILA
			MOV BP, SP
			; GUARDAMOS TODOS LOS REGISTROS QUE VAMOS A USAR EN LA PILA
			PUSH BX CX DX DI
			; GUARDAMOS EN BX EL SEGMENTO DE NUMSECRETO
			MOV BX, [BP + 8]
			; GUARDAMOS EL DS EN CX
			MOV CX, DS
			; PUSHEAMOS CX EN LA PILA
			PUSH CX
			; COLOCAMOS EL DATA SEGMENT EN EL SEGMENTO DE DATOS DE NUMSECRETO
			MOV DS, BX
			; GUARDAMOS EN DX EL SEGMENTO DE INTENTODIGITOS
			MOV DX, [BP + 12]
			; GUARDAMOS EN BX EL EXTRA SEGMENT
			MOV BX, ES
			; PUSHEAMOS BX EN LA PILA
			PUSH BX
			; COLOCAMOS EL EXTRA SEGMENT EN EL SEGMENTO DE DATOS DE INTENTODIGITOS
			MOV ES, DX
			; INICIALIZAMOS DI A 0
			MOV DI, 0
			; INICIALIZAMOS AX A 0, QUE LO UTILIZAREMOS COMO CONTADOR
			MOV AX, 0
			bucle:
				; GUARDAMOS EN BX EL OFFSET DE NUMSECRETO
				MOV BX, [BP + 6]
				; GUARDAMOS EN BX EL CONTENIDO DE UNA POSICION DE NUMSECRETO EN FUNCION DE DI
				MOV CH, DS:[BX][DI]
				; GUARDAMOS EN BX EL OFFSET DE INTENTODIGITOS
				MOV BX, [BP + 10]
				; GUARDAMOS EN DX EL CONTENIDO DE UNA POSICION DE INTENTODIGITOS EN FUNCION DE DI
				MOV DH, ES:[BX][DI]
				; COMPROBAMOS  SI LOS DOS NUMEROS SON IGUALES
				CMP CH, DH
				; SI SON IGUALES SALTAMOS A LA RUTINA ACIERTO
				JE acierto
				continuar:
					; INCREMENTAMOS EL INDICE DEL ARRAY
					INC DI
					; COMPROBAMOS SI HEMOS LLEGADO AL FINAL DEL ARRAY
					CMP DI, 4
					; SI EL INDICE NO ES IGUAL A 4 SEGUIMOS COMPROBANDO
					JNE bucle
					; UNA VEZ HEMOS TERMINADO LA COMPROBACION SALTAMOS A LA RUTINA FINAL
					JMP final
				acierto:
					; INCREMENTAMOS EL CONTADOR DE ACIERTOS
					ADD AX, 1
					; VOLVEMOS A LA RUTINA DE COMPROBACION
					JMP continuar
			final:
				; POPEAMOS EL SEGMENTO DE EXTRA SEGMENT Y COLOCAMOS EXTRA SEGMENT
				POP BX
				; COLOCAMOS EXTRA SEGMENT
				MOV ES, BX
				; POPEAMOS EL SEGMENTO DATA SEGMENT Y COLOCAMOS DATA SEGMENT
				POP BX
				; COLOCAMOS EL DATA SEGMENT
				MOV DS, BX
				; POPEAMOS LOS REGISTROS QUE HEMOS USADO
				POP DI DX CX BX
				; POPEAMOS EL BP 
				POP BP
				; VOLVEMOS AL PROGRAMA DE CMP
				RET
		_calcularAciertos ENDP
		
		_calcularSemiaciertos PROC FAR
			; PUSHEAMOS BP EN LA PILA
			PUSH BP
			; GUARDAMOS EN BP EL STACK POINTER DE LA PILA
			MOV BP, SP
			; GUARDAMOS LOS REGISTROS QUE VAMOS A USAR
			PUSH BX CX DX DI SI
			; GUARDAMOS EN BX EL SEGMENTO DE NUMSECRETO
			MOV BX, [BP + 8]
			; GUARDAMOS EL DATA SEGMENT EN CX
			MOV CX, DS
			; PUSHEAMOS EL DATA SEGMENT EN LA PILA
			PUSH CX
			; COLOCAMOS EL SEGMENTO DE DATOS CON EL DE NUMSECRETO
			MOV DS, BX
			; GUARDAMOS EN CX EL SEGMENTO DE INTENTODIGITOS
			MOV CX, [BP + 12]
			; GUARDAMOS EN DX EL EXTRA SEGMENT
			MOV DX, ES
			; PUSHEAMOS EL EXTRA SEGMENT EN LA PILA
			PUSH DX
			; COLOCAMOS EL EXTRA SEGMENT CON EL DE INTENTODIGITOS
			MOV ES, DX
			; INICIALIZAMOS DI A 0
			MOV DI, 0
			; INICIALIZAMOS AX A 0 PARA USARLO COMO CONTADOR
			MOV AX, 0
			comprobacion:
				; INICIALIZAMOS SI A 0
				MOV SI, 0
				; GUARDAMOS EN BX EL OFFSET DE NUMSECRETO
				MOV BX, [BP + 6]
				; GUARDAMOS EN DL EL CONTENIDO DE LA POSICION DI DE NUMSECRETO
				MOV DL, DS:[BX][DI]
				; GUARDAMOS EN BX EL OFFSET DE INTENTODIGITOS
				MOV BX, [BP + 10]
				bucle2:
					; GUARDAMOS EL CONTENIDO DE LA POSICION SI DE INTENTODIGITOS EN CL
					MOV CL, ES:[BX][SI]
					; COMPROBAMOS SI CL Y AL SON IGUALES
					CMP DL, CL
					; SI SON IGUALES SALTAMOS A LA RUTINA INCREMENTAR
					JE incrementar
					continuar2:
						; INCREMENTAMOS SI PARA SEGUIR COMPROBANDO EL ARRAY DE INTENTODIGITOS
						INC SI
						; COMPROBAMOS SI SI HA LLEGADO AL FINAL DE ARRAY
						CMP SI, 4
						; SI SI NO ES 4 CONTINUAMOS CON LA COMPROBACION
						JNE bucle2
					; INCREMENTAMOS DI
					INC DI
					; SI DI ES DISTINTO DE 4 CONTINUAMOS CON EL BUCLE PARA SEGUIR COMPROBANDO
					CMP DI, 4
					; SI NO ES IGUAL A 4 CONTINUAMOS CON EL BUCLE
					JNE comprobacion
				final2:
					; POPEAMOS EL SEGMENTO DE EXTRA SEGMENT Y COLOCAMOS EXTRA SEGMENT
					POP BX
					; COLOCAMOS EXTRA SEGMENT
					MOV ES, BX
					; POPEAMOS EL SEGMENTO DATA SEGMENT Y COLOCAMOS DATA SEGMENT
					POP BX
					; COLOCAMOS EL DATA SEGMENT
					MOV DS, BX
					; POPEAMOS TODOS LOS REGISTROS
					POP SI DI DX CX BX
					; POPEAMOS EL BP 
					POP BP
					; VOLVEMOS AL PROGRAMA DE CMP
					RET
				incrementar:
					; COMPROBAMOS SI ES UN ACIERTO TOTAL O PARCIAL
					CMP SI, DI
					; SI SON IGUALES CONTINUAMOS CON LA COMPROBACION
					JE continuar2
					; SI NO SON IGUALES INCREMENTAMOS AX
					ADD AX, 1
					; SEGUIMOS COMPROBANDO LOS ARRAYS
					JMP continuar2
			
		_calcularSemiaciertos ENDP
		
PRACT3B ENDS ; FIN DEL SEGMENTO DE CODIGO
END ; FIN DE pract3a.asm