#ifndef SENIALES_H
#define SENIALES_H

/*ESTE MANEJADOR CONTROLA LA SENIAL CTRL + C ENVIADA POR EL USUARIO*/
void manejador_SIGINT(int sig);

/*ESTE MANEJADOR CONTROLA LA SENIAL DE FIN DE TIEMPO ENVIADA POR EL PROCESO MONITOR AL PROCESO PRINCIPAL*/
void manejador_SIGALRM(int sig);

/*ESTE MANEJADAOR CONTROLA LA SENIAL QUE ENVIA EL PROCESO PRINCIPAL PARA QUE LOS CABALLOS REALICEN SU TIRADA*/
void manejador_SIGUSR1(int sig);

/*ESTE MANEJADOR LO UTILIZARA EL PROCESO PRINCIPAL PARA AVISAR A LOS PROCESOS APOSTANTES DE QUE SE HA ACABADO EL TIEMPO DE REALIZAR APUESTAS*/
void manejador_SIGUSR2(int sig);

/*ESTE MANEJADOR LO UTILIZARA EL PROCESO PRINCIPAL PARA AVISAR AL PROCESO GESTOR DE APUESTAS DE QUE SE HA ACABADO EL TIEMPO DE REALIZAR APUESTAS*/
void manejador_SIGTERM(int sig);

/*ESTE MANEJADOR LO UTILIZARAN LOS HILOS PARA SABER CUANDO DEBEN DE TERMINAR DE LEER MENSAJES DE LA COLA DE MENSAJES*/
void manejador_SIGTRAP(int sig);

/*ESTE MANEJADOR AVISA AL PROCESO MONITOR QUE SE HA ACABADO LA CARRERA*/
void manejador_SIGSYS(int sig);

#endif